name: Fetch GitHub Repo Contents

on:
  push:
    branches:
      - main

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch Full Repo Contents
        run: |
          # Fetch and store full repo contents recursively
          echo '[]' > repo_data.json  # Initialize empty JSON array
      
          fetch_contents() {
            local url=$1
            local token="${{ secrets.PAT }}"
            
            # Get contents from the given URL and add to repo_data.json
            curl -s -H "Authorization: token $token" \
                    -H "Accept: application/vnd.github.v3+json" \
                    "$url" | jq -c '.[]' >> repo_data.json
            
            # Iterate over directories and recursively fetch contents
            curl -s -H "Authorization: token $token" \
                    -H "Accept: application/vnd.github.v3+json" \
                    "$url" | jq -c '.[] | select(.type=="dir")' | while read dir; do
              dir_url=$(echo "$dir" | jq -r '.url')
              fetch_contents "$dir_url"
            done
          }
      
          # Start fetching from the root of the repo
          fetch_contents "https://api.github.com/repos/CS401W2018/projects-DanielH987/contents/"
          
          # Format JSON as an array (not one object per line)
          jq -s '.' repo_data.json > formatted_repo_data.json
          mv formatted_repo_data.json repo_data.json      

      - name: Set up Git Config
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions"

      - name: Ensure gh-pages Exists
        run: |
          git fetch origin gh-pages || echo "No gh-pages branch yet"
          if git show-ref --verify --quiet refs/heads/gh-pages; then
            git checkout gh-pages
          else
            git checkout --orphan gh-pages
          fi

      - name: Commit and Push Data
        run: |
          git add repo_data.json
          git commit -m "Update repo contents" || echo "No changes to commit"
          git push --force origin gh-pages