name: Fetch GitHub Repo Contents

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch Repo Contents
        run: |
          curl -H "Authorization: token ${{ secrets.PAT }}" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/cs401w2018/projects-DanielH987/contents/ > repo_data.json

      - name: Push Data to gh-pages
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions"
          git checkout gh-pages || git checkout -b gh-pages
          mv repo_data.json .
          git add repo_data.json
          git commit -m "Update repo contents"
          git push origin gh-pages