name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build and Deploy
        env:
          GITHUB_PAT: ${{ secrets.PAT }}
        run: |
          # Replace this with your build and deployment process
          echo "const token = '${GITHUB_PAT}';" > token.js
          # Deploy to GitHub Pages (or build the project if needed)
          echo "Token injected into token.js"
